#!/bin/sh

commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")

# Define a regular expression pattern to match the desired format
pattern="^:[a-zA-Z]+: [a-zA-Z]+: .+ #[0-9]+$"

if ! echo "$commit_msg" | grep -qE "$pattern"; then
  echo "O formato da mensagem de commit é inválido." 
  echo "Utilize o seguinte formato \":emoji: tipi: mensagem do commit #número do issue\"." >&2
  echo "Deseja continuar mesmo assim? (y/n)"
  exec < /dev/tty
  read continue
  if [ "$continue" != "y" ]; then
    exit 1
  fi
fi
