#!/bin/sh

commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")

# Define a regular expression pattern to match the desired format
pattern="^:[a-zA-Z]+: [a-zA-Z]+: .+ #[0-9]+$"

if ! echo "$commit_msg" | grep -qE "$pattern"; then
  echo "Invalid commit message format. Please use the format \":anything: anything: anything anything #num\"." >&2
  exit 1
fi
